Changes for PowerAPI monitoring

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,166 +1,198 @@
-name: CI
-on: [push, pull_request, workflow_dispatch]
 jobs:
-  # C implementation. Lives in c/, tested with bazel.
   test-c:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: c
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v2
-      - name: test
-        run: bazel test --test_output=all ${OLC_PATH}:all
-      - name: check formatting
-        run: cd ${OLC_PATH} && bash clang_check.sh
-        
-  # C++ implementation. Lives in cpp/, tested with bazel.
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      name: test
+      run: bazel test --test_output=all ${OLC_PATH}:all
+    - continue-on-error: true
+      name: check formatting
+      run: cd ${OLC_PATH} && bash clang_check.sh
   test-cpp:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: cpp
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v2
-      - name: test
-        run: bazel test --test_output=all ${OLC_PATH}:all
-      - name: check formatting
-        run: cd ${OLC_PATH} && bash clang_check.sh
-        
-  # Dart implementation. Lives in dart/.
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      name: test
+      run: bazel test --test_output=all ${OLC_PATH}:all
+    - continue-on-error: true
+      name: check formatting
+      run: cd ${OLC_PATH} && bash clang_check.sh
   test-dart:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: dart
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v2
-      - uses: dart-lang/setup-dart@v1
-      - name: test
-        run: |
-          cd ${OLC_PATH}
-          pub get && pub run test
-          bash checks.sh
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      uses: dart-lang/setup-dart@v1
+    - continue-on-error: true
+      name: test
+      run: 'cd ${OLC_PATH}
 
-  # Go implementation. Lives in go/. Tests fail if files have not been formatted with gofmt.
+        pub get && pub run test
+
+        bash checks.sh
+
+        '
   test-go:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: go
+    runs-on: self-hosted
     steps:
-    - uses: actions/checkout@v2
-    - uses: actions/setup-go@v2
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      uses: actions/setup-go@v2
       with:
         go-version: 1.17
-    - name: test
-      run: |
-        cd ${OLC_PATH}
+    - continue-on-error: true
+      name: test
+      run: 'cd ${OLC_PATH}
+
         diff -u <(echo -n) <(gofmt -d -s ./)
+
         go test -bench=. ./ -v
-    - name: test-gridserver
-      run: |
-        cd tile_server/gridserver
+
+        '
+    - continue-on-error: true
+      name: test-gridserver
+      run: 'cd tile_server/gridserver
+
         go test ./ -v
-        
-  # Java implementation. Lives in java/, tested with bazel and maven.     
+
+        '
   test-java:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: java
+    name: test-java-${{ matrix.java }}
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      name: Setup java
+      uses: actions/setup-java@v2
+      with:
+        distribution: temurin
+        java-version: ${{ matrix.java }}
+    - continue-on-error: true
+      name: test
+      run: bazel test --test_output=all ${OLC_PATH}:all && cd ${OLC_PATH} && mvn package
     strategy:
       matrix:
-        java: [ '8', '11', '16', '17' ]
-    name: test-java-${{ matrix.java }}
-    steps:
-      - uses: actions/checkout@v2
-      - name: Setup java
-        uses: actions/setup-java@v2
-        with:
-          distribution: 'temurin'
-          java-version: ${{ matrix.java }}
-      - name: test
-        run: bazel test --test_output=all ${OLC_PATH}:all && cd ${OLC_PATH} && mvn package
-        
-  # Javascript Closure library implementation. Lives in js/closure, tested with bazel.  
-  test-js-closure:
-    runs-on: ubuntu-latest
-    env:
-      OLC_PATH: js/closure
-    steps:
-      - uses: actions/checkout@v2
-      - name: test
-        run: |
-          bazel test ${OLC_PATH}:all
-          cd js && npm install && ./node_modules/.bin/eslint closure/*js
-
-  # Javascript implementation. Lives in js/.
+        java:
+        - '8'
+        - '11'
+        - '16'
+        - '17'
   test-js:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: js
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v2
-      - name: test
-        run: |
-          cd ${OLC_PATH}
-          bash checks.sh
-          
-  # Python implementation. Lives in python/, tested with bazel.
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      name: test
+      run: 'cd ${OLC_PATH}
+
+        bash checks.sh
+
+        '
+  test-js-closure:
+    env:
+      OLC_PATH: js/closure
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      name: test
+      run: 'bazel test ${OLC_PATH}:all
+
+        cd js && npm install && ./node_modules/.bin/eslint closure/*js
+
+        '
   test-python:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: python
+    name: test-python-${{ matrix.python }}
+    runs-on: self-hosted
+    steps:
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python }}
+    - continue-on-error: true
+      name: test
+      run: bazel test --test_output=all ${OLC_PATH}:all
+    - continue-on-error: true
+      name: check formatting
+      run: "cd ${OLC_PATH}\npip install yapf\nDIFF=`python -m yapf --diff *py`\nif\
+        \ [ $? -eq 0 ]; then\n  echo -e \"Python files are correctly formatted\"\n\
+        \  exit 0\nelse \n  echo -e \"Python files have formatting errors\"\n  echo\
+        \ -e \"These must be corrected using format_check.sh\"\n  echo \"$DIFF\"\n\
+        fi\nexit 1\n"
     strategy:
       matrix:
-        python: [ '2.7', '3.6', '3.7', '3.8' ]
-    name: test-python-${{ matrix.python }}
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python 
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python }}
-      - name: test
-        run: bazel test --test_output=all ${OLC_PATH}:all
-      - name: check formatting
-        run: |
-          cd ${OLC_PATH}
-          pip install yapf
-          DIFF=`python -m yapf --diff *py`
-          if [ $? -eq 0 ]; then
-            echo -e "Python files are correctly formatted"
-            exit 0
-          else 
-            echo -e "Python files have formatting errors"
-            echo -e "These must be corrected using format_check.sh"
-            echo "$DIFF"
-          fi
-          exit 1
-          
-  # Ruby implementation. Lives in ruby/.
+        python:
+        - '2.7'
+        - '3.6'
+        - '3.7'
+        - '3.8'
   test-ruby:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: ruby
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v2
-      - uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: '2.6'
-      - name: test
-        run: |
-          gem install rubocop
-          gem install test-unit
-          cd ${OLC_PATH} && ruby test/plus_codes_test.rb
-          rubocop --config rubocop.yml
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      uses: ruby/setup-ruby@v1
+      with:
+        ruby-version: '2.6'
+    - continue-on-error: true
+      name: test
+      run: 'gem install rubocop
 
-  # Rust implementation. Lives in rust/.
+        gem install test-unit
+
+        cd ${OLC_PATH} && ruby test/plus_codes_test.rb
+
+        rubocop --config rubocop.yml
+
+        '
   test-rust:
-    runs-on: ubuntu-latest
     env:
       OLC_PATH: rust
+    runs-on: self-hosted
     steps:
-      - uses: actions/checkout@v2
-      - name: test
-        run: |
-          cd ${OLC_PATH}
-          cargo fmt --all -- --check
-          cargo build
-          cargo test -- --nocapture
+    - continue-on-error: true
+      uses: actions/checkout@v2
+    - continue-on-error: true
+      name: test
+      run: 'cd ${OLC_PATH}
+
+        cargo fmt --all -- --check
+
+        cargo build
+
+        cargo test -- --nocapture
+
+        '
+name: CI
+on:
+  repository_dispatch:
+    types: trigger-ga___main.yml
